In [1]:
import numpy as np

x = np.random.random([2, 2])

print(x)

[[0.60346613 0.91930989]
 [0.70613796 0.24616677]]


In [3]:
x[0]

array([0.60346613, 0.91930989])

In [6]:
squared = x**2.0
print(squared)

[[0.36417137 0.84513068]
 [0.49863081 0.06059808]]


In [8]:
np.sum(x**2.0, axis=0)

array([0.86280219, 0.90572875])

In [9]:
np.sum(x**2.0, axis=1)

array([1.20930205, 0.55922889])

axis=0 gets the sum vertically

axis=1 gets the sume horizontally

Refrence:

https://jimmy-ai.tistory.com/116